version: '3.8'

services:
  # NATS for testing
  nats-test:
    image: nats:2.10-alpine
    container_name: nats-server-test
    command: ['-p', '4223', '-m', '8223']
    ports:
      - '4223:4223'
      - '8223:8223'
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost:8223/varz | grep -q uptime']
      interval: 10s
      timeout: 5s
      retries: 5

  # User Service Test Database
  user_db_test:
    image: postgres:16-alpine
    container_name: user_db_test
    environment:
      POSTGRES_DB: user_db_test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
    ports:
      - '5533:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d user_db_test']
      interval: 10s
      timeout: 5s
      retries: 5

  # Product Service Test Database
  product_db_test:
    image: postgres:16-alpine
    container_name: product_db_test
    environment:
      POSTGRES_DB: product_db_test
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product_password
    ports:
      - '5534:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U product -d product_db_test']
      interval: 10s
      timeout: 5s
      retries: 5

  # Cart Service Test Database
  cart_db_test:
    image: postgres:16-alpine
    container_name: cart_db_test
    environment:
      POSTGRES_DB: cart_db_test
      POSTGRES_USER: cart
      POSTGRES_PASSWORD: cart_password
    ports:
      - '5535:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U cart -d cart_db_test']
      interval: 10s
      timeout: 5s
      retries: 5

  # Order Service Test Database
  order_db_test:
    image: postgres:16-alpine
    container_name: order_db_test
    environment:
      POSTGRES_DB: order_db_test
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order_password
    ports:
      - '5536:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U order -d order_db_test']
      interval: 10s
      timeout: 5s
      retries: 5

  # Payment Service Test Database
  payment_db_test:
    image: postgres:16-alpine
    container_name: payment_db_test
    environment:
      POSTGRES_DB: payment_db_test
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment_password
    ports:
      - '5537:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U payment -d payment_db_test']
      interval: 10s
      timeout: 5s
      retries: 5

  # AR Service Test Database
  ar_db_test:
    image: postgres:16-alpine
    container_name: ar_db_test
    environment:
      POSTGRES_DB: ar_db_test
      POSTGRES_USER: ar
      POSTGRES_PASSWORD: ar_password
    ports:
      - '5538:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ar -d ar_db_test']
      interval: 10s
      timeout: 5s
      retries: 5

  # Report Service Test Database
  report_db_test:
    image: postgres:16-alpine
    container_name: report_db_test
    environment:
      POSTGRES_DB: report_db_test
      POSTGRES_USER: report
      POSTGRES_PASSWORD: report_password
    ports:
      - '5539:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U report -d report_db_test']
      interval: 10s
      timeout: 5s
      retries: 5
