### Variables
@baseUrl = http://localhost:3000
@accessToken = YOUR_ACCESS_TOKEN_HERE

### List user's addresses
GET {{baseUrl}}/addresses
Authorization: Bearer {{accessToken}}

### Create new address
POST {{baseUrl}}/addresses
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "fullName": "Nguyen Van A",
  "phone": "0123456789",
  "street": "123 Le Loi",
  "ward": "Phuong 1",
  "district": "Quan 1",
  "city": "TP.HCM",
  "isDefault": true
}

### Update address
PUT {{baseUrl}}/addresses/ADDRESS_ID_HERE
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "fullName": "Nguyen Van B",
  "phone": "0987654321",
  "street": "456 Nguyen Hue"
}

### Delete address
DELETE {{baseUrl}}/addresses/ADDRESS_ID_HERE
Authorization: Bearer {{accessToken}}

### Set default address
PUT {{baseUrl}}/addresses/ADDRESS_ID_HERE/set-default
Authorization: Bearer {{accessToken}}